export const ordersArray = [
  {
    id: "53200002",
    products: "5 items",
    date: "Jan 20, 2024",
    customer: "Ronald Jones",
    status: "Pending",
    quantity: 5,
    city: "New York",
    totalAmount: 50,
  },
  {
    id: "53200003",
    products: "3 items",
    date: "Jan 15, 2024",
    customer: "Jacob McKinney",
    status: "Completed",
    quantity: 3,
    city: "Los Angeles",
    totalAmount: 966.1,
  },
  {
    id: "53200004",
    products: "8 items",
    date: "Jan 20, 2024",
    customer: "Isabella Murphy",
    status: "Shipping",
    quantity: 8,
    city: "Chicago",
    totalAmount: 98.25,
  },
  {
    id: "42100003",
    products: "2 items",
    date: "Jan 25, 2024",
    customer: "John McKinney",
    status: "Completed",
    quantity: 2,
    city: "New York",
    totalAmount: 156.41,
  },
  {
    id: "78100003",
    products: "5 items",
    date: "Jan 28, 2024",
    customer: "Diana Cooper",
    status: "Pending",
    quantity: 5,
    city: "Rome",
    totalAmount: 556.41,
  },
  {
    id: "98100003",
    products: "6 items",
    date: "Feb 5, 2024",
    customer: "Gregory",
    status: "Shipping",
    quantity: 6,
    city: "United State",
    totalAmount: 700.41,
  },
];
